# CREATE TABLE `products` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`NAME` TEXT NOT NULL,
# 	`ACTIVE` BOOLEAN NOT NULL DEFAULT FALSE,
# 	`CATEGORY_ID` INT NOT NULL DEFAULT 1,
# 	`COMMENT` TEXT,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL DEFAULT 1,
# 	`IMAGE_PATH` TEXT,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `categories` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`NAME` TEXT NOT NULL,
# 	`ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
# 	`COMMENT` TEXT,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL DEFAULT 1,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `warehouses` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`PRODUCT_ID` INT NOT NULL,
# 	`AMOUNT` FLOAT DEFAULT 0,
# 	`RESERVE` FLOAT DEFAULT 0,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL DEFAULT 1,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `prices` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`PRODUCT_ID` INT NOT NULL,
# 	`ITEM_MEASURE` TEXT NOT NULL,
# 	`ITEM_PRICE` FLOAT NOT NULL,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL DEFAULT 1,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `manufacturers` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`NAME` TEXT NOT NULL,
# 	`ADDRESS` TEXT NOT NULL,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `productions` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`PRODUCT_ID` INT NOT NULL,
# 	`MANUFACTURER_ID` INT NOT NULL,
# 	`WAREHOUSE_ID` INT NOT NULL,
# 	`AMOUNT` FLOAT DEFAULT 0,
# 	`DATE` DATETIME NOT NULL,
# 	`COMMENT` TEXT,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `pickpoints` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`ADDRESS` TEXT NOT NULL,
# 	`WORKHOURS` TEXT,
# 	`COMMENT` TEXT,
# 	`ACTIVE` BOOLEAN NOT NULL DEFAULT FALSE,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `orders` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`COMMENT` TEXT NOT NULL,
# 	`ORDER_DATE` DATETIME NOT NULL,
# 	`STATUS` TEXT NOT NULL,
# 	`DELIVERY_DATE` DATETIME NOT NULL,
# 	`PAYMENT_TYPE` VARCHAR(128),
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `order_contents` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`DATE` DATETIME NOT NULL,
# 	`COMMENT` TEXT NOT NULL,
# 	`ORDER_ID` INT NOT NULL,
# 	`PRODUCT_ID` INT NOT NULL,
# 	`MANUFACTURER_ID` INT NOT NULL,
# 	`WAREHOUSE_ID` INT NOT NULL,
# 	`AMOUNT` FLOAT DEFAULT 0,
# 	`PRICE_ID` INT NOT NULL,
# 	`STATUS` TEXT NOT NULL,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`AUTHOR_ID` INT NOT NULL,
# 	PRIMARY KEY (`ID`)
# );
#
#
# CREATE TABLE `users` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`GUID` VARCHAR(255) NOT NULL,
# 	`LOGIN` VARCHAR(255) NOT NULL,
# 	`PASSWORD` VARCHAR(255) NOT NULL,
# 	`ROLE` INT NOT NULL,
# 	`FIO` VARCHAR(255) NOT NULL,
# 	`EMAIL` VARCHAR(255) NOT NULL,
# 	`PHONE` VARCHAR(20) NOT NULL,
# 	`AUTH_SOURCE` INT NOT NULL,
# 	`CREATED` DATETIME NOT NULL,
# 	`UPDATED` DATETIME NOT NULL,
# 	`ACTIVE` BOOLEAN NOT NULL,
# 	PRIMARY KEY (`ID`)
# );
#
# CREATE TABLE `user_roles` (
# 	`ID` INT NOT NULL AUTO_INCREMENT,
# 	`TITLE` VARCHAR(255) NOT NULL,
# 	`DESCRIPTION` TEXT,
# 	`CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
# 	`UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
# 	`ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
# 	PRIMARY KEY (`ID`)
# );
######
# INSERT INTO user_roles(`TITLE`) VALUES (N'Администратор'),(N'Сыровар'),(N'Покупатель')

CREATE TABLE `cart` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`BUYER` INT NOT NULL,
	`PRODUCT` INT NOT NULL,
	`AMOUNT` int NOT NULL,
	`PRICE` INT NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`ACTIVE` BOOLEAN NOT NULL,
	PRIMARY KEY (`ID`)
);
